# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6  # Use sempre a versão estável mais recente do Ruff
    hooks:
      # Hook 1: Roda o linter do Ruff. Ele irá bloquear o commit se houverem erros.
      - id: ruff
        args: [ --fix ] # Adiciona o --fix para tentar corrigir problemas simples

      # Hook 2: Roda o formatador do Ruff. Ele irá reformatar arquivos alterados.
      - id: ruff-format
